name: html,css,js 오류 검사

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint HTML
        run: |
          curl -X POST --data-binary @index.html "https://validator.w3.org/nu/?out=json"
          echo "HTML linting completed."

      - name: Lint CSS
        run: |
          CSS_CONTENT=$(cat style.css)
          curl -s --data-urlencode "text=${CSS_CONTENT}" --data "profile=css3&output=json" "https://jigsaw.w3.org/css-validator/validator"
          echo "CSS linting completed."

      - name: Lint JS
        run: |
          npm install -g jshint
          jshint script.js
          echo "JS linting completed."

      - name: Create Issue for Errors
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create --title "Linting Errors Detected" --body "Linting found errors in the code. Please review!"
